name: 'Continuous Integration'

on:
  pull_request: ~
  push:
    branches: [ master ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
      - name: 'Unit Tests (PHP 7.4)'
        uses: php-actions/phpunit@v3
        with:
          php_version: '7.4'
      - name: 'Unit Tests (PHP 8.0)'
        uses: php-actions/phpunit@v3
        with:
          php_version: '8.0'
      - name: 'Unit Tests (PHP 8.1)'
        uses: php-actions/phpunit@v3
        with:
          php_version: '8.1'
      - name: 'Unit Tests (PHP 8.2)'
        uses: php-actions/phpunit@v3
        with:
          php_version: '8.2'
