name: 'Continuous Integration'

on:
  pull_request: ~
  push:
    branches: [ master ]

jobs:
  unit-tests:
    name: "Unit Tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
    steps:
      - name: 'Checkout The Code'
        uses: actions/checkout@v3
      - name: 'Install Dependencies'
        uses: php-actions/composer@v6
      - name: 'Run Unit Tests'
        run: vendor/bin/phpunit tests
